#!/usr/bin/env python

import random


def randomMAC():
    mac = [0xDE, 0xAD, 0xBE, 0xEF,
           random.randint(0x00, 0xff),
           random.randint(0x00, 0xff)]
    return ':'.join(map(lambda x: "%02x" % x, mac))


print(randomMAC())
