#!/usr/bin/env perl

use strict;
use warnings;

sub print_help()
{
my $help_message = <<HELP_MESSAGE;
raw commands:
nosleep : sudo pmset -b sleep 0; sudo pmset -b disablesleep 1
sleep : sudo pmset -b sleep 5; sudo pmset -b disablesleep 0
HELP_MESSAGE

    print $help_message;
}

my $cmd = $ARGV[0] // '';

if ($cmd eq "nosleep") {
    system("sudo pmset -b sleep 0; sudo pmset -b disablesleep 1");
}
elsif ($cmd eq "sleep") {
    system("sudo pmset -b sleep 5; sudo pmset -b disablesleep 0");
}
else {
    print_help();
}
