#!/usr/bin/env perl

use strict;
use warnings;

# Detect OS and set appropriate top command
my $os = `uname`;
chomp($os);

my @topsum;
if ($os eq "Darwin") {
    @topsum = `top -l 1 -n 0`;
} else {
    @topsum = `top -n 1 -b`;
}

my %cumulativemem;
my $inlist = 0;

foreach my $line (@topsum)
{
    if ($inlist == 1)
    {
        my @curline = split(/\s+/,$line);
        # Handle different column positions for different OS
        if ($os eq "Darwin") {
            # macOS: MEM column is different
            $cumulativemem{$curline[1]}[0] += $curline[7] if defined $curline[7];
            ++$cumulativemem{$curline[1]}[1];
        } else {
            # Linux
            $cumulativemem{$curline[-1]}[0] += $curline[-3];
            ++$cumulativemem{$curline[-1]}[1];
        }
    }
    $inlist = 1 if ($line =~ /^\s*PID/ || $line =~ /^PID/);
}

print "\n\tMem%\tCmd [num instances]\n\n";

my $count = 0;
foreach (sort {$cumulativemem{$b}[0] <=> $cumulativemem{$a}[0]} keys %cumulativemem)
{
    print "\t$cumulativemem{$_}[0]\t$_ \[$cumulativemem{$_}[1]\]\n" if ($cumulativemem{$_}[0] > 0);
    ++$count;
    if ($count == 25) {print "\n"; last}
}
