#!/usr/bin/env perl

use strict;
use warnings;

my $num_procs = $ARGV[0] || 500;

my $os = `uname`;
chomp($os);

my @topsum;
if ($os eq "Darwin") {
    @topsum = `top -l 1 -n $num_procs`;
} else {
    @topsum = `top -n 1 -b`;
}

my %cumulativemem;
my $inlist = 0;

foreach my $line (@topsum)
{
    if ($inlist == 1)
    {
        $line =~ s/^\s+//;
        my @curline = split(/\s+/,$line);

        if ($os eq "Darwin") {
            my $cmd = $curline[1];
            my $mem = $curline[7];

            if (defined $mem && $mem =~ /^(\d+(?:\.\d+)?)(K|M|G|B)/) {
                my ($val, $unit) = ($1, $2);
                my $kb = 0;

                if ($unit eq 'K') { $kb = $val; }
                elsif ($unit eq 'M') { $kb = $val * 1024; }
                elsif ($unit eq 'G') { $kb = $val * 1024 * 1024; }
                elsif ($unit eq 'B') { $kb = $val / 1024; }

                $cumulativemem{$cmd}[0] += $kb;
                ++$cumulativemem{$cmd}[1];
            }
        } else {
            $cumulativemem{$curline[-1]}[0] += $curline[-3];
            ++$cumulativemem{$curline[-1]}[1];
        }
    }
    $inlist = 1 if ($line =~ /^\s*PID/ || $line =~ /^PID/);
}

if ($os eq "Darwin") {
    print "\n\tMem(MB)\tCmd [num instances]\n\n";
} else {
    print "\n\tMem%\tCmd [num instances]\n\n";
}

my $count = 0;
foreach (sort {$cumulativemem{$b}[0] <=> $cumulativemem{$a}[0]} keys %cumulativemem)
{
    if ($cumulativemem{$_}[0] > 0) {
        my $mem_display;
        if ($os eq "Darwin") {
            $mem_display = sprintf("%.1fM", $cumulativemem{$_}[0] / 1024);
        } else {
            $mem_display = $cumulativemem{$_}[0];
        }
        print "\t$mem_display\t$_ \[$cumulativemem{$_}[1]\]\n";
    }
    ++$count;
    if ($count == 25) {print "\n"; last}
}
